name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: designsafeci/ds-use-case-template:latest
      -
        name: Post build status in slack
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "build_status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
